### ISSUE TITLE
Enable hosting brand assets and resources

### ISSUE THREAD

**Issue by cjeria** [MetaMask/website#11]
**Web Team Ticket:** 

https://github.com/ConsenSys/dx-team/issues/1549

**Desc:**

Let's host subpage for all brand assets and resources. For starters, let's just do our logos as an SVG. The fox svg can be found [here](https://github.com/MetaMask/brand-resources/blob/master/SVG/metamask-fox.svg). The assets should be stored under a path like `assets/`. The icon would then be `assets/icon.svg`.

**Comment by jlazoff** [comment]
Hi @cjeria ,
Do you happen to have any updates on this ticket? If active, we can scope it...

**Comment by cuonglt-ync** [comment]
Hi [cjeria](https://github.com/cjeria), @jlazoff,

Please let me know the scope in detail. Thank you.

**Comment by rekmarks** [comment]
@jlazoff I updated the description.

**Comment by jlazoff** [comment]
Hi @cjeria ,

The staging site is ready, can you help us finish this ticket? Dev Team Ticket: https://github.com/Consensys/dx-team/issues/1549

Staging URL: https://metamask.consensys.io/assets/

Much appreciated!,

Joshua 

➿ @worldlyjohn @lorenzosantos

**Comment by jlazoff** [comment]
Page live! https://metamask.io/assets/
