### ISSUE TITLE
Forms don't have dark mode support 

### ISSUE THREAD

**Issue by brendankirby** [MetaMask/website#172]
YNS: https://jira.younetco.com/browse/CFCONSENSYS-1061

https://metamask.io/institutions
<img width="766" alt="Screen Shot 2022-09-23 at 11 52 00 AM" src="https://user-images.githubusercontent.com/3248787/192039919-7836df56-523b-494b-b080-0b22883e25ce.png">

The Request Access and Download Brochure forms in the Institutions page don't have the correct formatting for dark mode. The text is difficult to read with the dark background. 
Reproducible on desktop and mobile browsers

**Comment by spiritanand** [comment]
I would love to make the CSS right for this form.

**Comment by spiritanand** [comment]
@jlazoff can I start on this?

**Comment by jlazoff** [comment]
> @jlazoff can I start on this?

Not yet; we need to make internal changes to the form. I have already submitted the request. Once complete, aiming for EOW, the form should be fixed. 🚀

**Comment by spiritanand** [comment]
How can I contribute to Metamask?

**Comment by SunnySian** [comment]
All forms have been set to raw HTML for styling purposes. Over to you.

**Comment by jlazoff** [comment]
Thank you!On Feb 10, 2023, at 7:44 AM, SunnySian ***@***.***> wrote:﻿
All forms have been set to raw HTML for styling purposes. Over to you.

**Comment by jlazoff** [comment]
Thank you all; we have resolved this issue. Closing ticket 🚀
