### ISSUE TITLE
Update security at metamask email everywhere

### ISSUE THREAD

**Issue by holantonela** [MetaMask/website#176]
We have a number of places on the website that point to `security@metamask.io`. We're going to be disabling that address and would like to replace all instances of it with `metamask.security@consensys.net`.

**Comment by spiritanand** [comment]
Can I work on this issue?

**Comment by jlazoff** [comment]
Hi @spiritanand , 
This work has been completed in ticket https://github.com/ConsenSys/dx-team/issues/1377 . Let me know if there is further work, we can re-open the ticket...

**Comment by spiritanand** [comment]
So will this issue be closed soon?

**Comment by jlazoff** [comment]
Closed :)On Jan 30, 2023, at 1:11 PM, Suryansh Anand ***@***.***> wrote:﻿
So will this issue be closed soon?
