### ISSUE TITLE
Broken link to Template Snap on Flask page

### ISSUE THREAD

**Issue by brendankirby** [MetaMask/website#180]
There is a broken link to the Template Snap on the Flask page. 

Page: https://metamask.io/flask/
Broken link: https://metamask.github.io/template-snap/

1. Scroll to the "Built for Developers" section
2. Click "Try out a live Snap with MetaMask Flask here" 

Result: Leads to a missing page. I believe the link should be "https://github.com/MetaMask/template-snap"

<img width="517" alt="Screen Shot 2022-10-11 at 12 25 46 PM" src="https://user-images.githubusercontent.com/3248787/195181358-f9659126-4b01-4432-80c8-08b63165545d.png">

**Comment by Montoya** [comment]
This has been fixed, thank you for reporting!
