### ISSUE TITLE
`yarn install` fails with Python  `>=3.11`

### ISSUE THREAD

**Issue by ritave** [MetaMask/website#236]
CSI Ticket: https://github.com/ConsenSys/dx-team/issues/1511

`node-gyp` fails to run during installation of `gatsby-cli` due to `ValueError: invalid mode: 'rU' while trying to load binding.gyp`.

This is because `U` mode has been removed in Python 3.11.

[Upgrading node-gyp will solve the problem.](https://github.com/nodejs/node-gyp/issues/2219)

**Comment by jlazoff** [comment]
**Ticket Update:**

Created a development ticket to address this: https://github.com/ConsenSys/dx-team/issues/1511 

Keep this ticket posted,

Joshua
