### ISSUE TITLE
[Metamask] Missing a security audit on our audits page

### ISSUE THREAD

**Issue by Montoya** [MetaMask/website#245]
Internal Ticket: https://github.com/ConsenSys/dx-team/issues/1525 

Our security page is missing one of the audits that was done in the past: 

https://leastauthority.com/blog/audits/metamask_plugin_system_lavamoat_audit/

See https://metamask.io/security/

[I am attaching the PDF of the audit report.](https://github.com/MetaMask/website/files/11335776/LeastAuthority-MetaMask-Plugin-System-LavaMoat-Audit-Report.pdf) Please add it to the list like so: 

* Cure53 - August 2017 - [Report](https://metamask.io/files/pentest-report_metamask.pdf)
* Least Authority - April 2019 - [Report](https://metamask.io/files/LeastAuthority-MetaMask-Audit-Report.pdf)
* Least Authority - March 2020 - [Report](https://metamask.io/files/LeastAuthority-MetaMask-Plugin-System-LavaMoat-Audit-Report.pdf)
* Cure53 - March 2023 - [Report](https://metamask.io/files/key-tree-audit-report.pdf)

**Comment by cuonglt-ync** [comment]
Hi [Montoya](https://github.com/Montoya),

You can manage the content via Contenful. 
https://app.contentful.com/spaces/9sy2a0egs6zh/environments/master/entries/6QILLdyeB1Vn0RdAQAvw3y

**Comment by jlazoff** [comment]
Pushed to prod 🚀
