### ISSUE TITLE
[Metamask] Snaps page button is not centered

### ISSUE THREAD

**Issue by Montoya** [MetaMask/website#272]
**YNC:** https://jira.younetco.com/browse/CFCONSENSYS-1240

**URLs:**
   * Primary URL: https://metamask.io/snaps/
   * Figma URL:

#### **Details:**

Live in MetaMask Flask button is not centered. See screenshot below. This is left-aligned but it is supposed to be centered. 

**Screenshots** 

<img width="770" alt="Screenshot 2023-08-03 at 11 52 45 AM" src="https://github.com/MetaMask/website/assets/19909/38671626-b876-48b0-866f-3fcc0986ef39">

**Additional context**

**Comment by jlazoff** [comment]
Resolved 🚀
