### ISSUE TITLE
Add bug-bounty page

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/website#5]
We need a highly visible place for security researchers to find our bug bounty program and learn our preferred process of responsible disclosure.

Example of our current biggest bug bounty:
https://github.com/MetaMask/metamask-extension/issues/3127

A couple examples from other projects:
- https://aave.com/bug-bounty
- https://www.argent.xyz/argent-bug-bounty/

**Comment by jlazoff** [comment]
Created already :) https://metamask.io/security/
