### ISSUE TITLE
Allow installing firefox extension directly from web page

### ISSUE THREAD

**Issue by danfinlay** [MetaMask/website#56]
This isn't possible for Chrome, but I have learned that [Nuance does this here](https://dnsriacontent.nuance.com/15/setup/ffinstall.html?lang=enx&version=15.61.200.10) for Firefox, so it should be possible for us too.

**Comment by jlazoff** [comment]
Hi,
This quicker way to download using the firefox browser has been implemented on staging.

Please review on a firefox browser 🚀
