### ISSUE TITLE
Heroku autoinvite is out of Slack invites

### ISSUE THREAD

**Issue by 10a7** [MetaMask/Website#62]
Not sure where to file this, but right now it's impossible to use the Slack link on the homepage to get an invite for the Slack channel. The application fails with `invite_limit_reached`.

**Comment by danfinlay** [comment]
We were about to take down the slack page because it was getting filled with phishers, and then this limit was reached, and now suddenly the influx of phishers has ended.

I would recommend new users join another channel, like our Gitter channel: https://gitter.im/MetaMask

**Comment by kumavis** [comment]
We removed this - thanks!
