### ISSUE TITLE
https://github.com/trufflesuite/drizzle

### ISSUE THREAD

**Issue by SvenMeyer** [MetaMask/Website#76]
Version 68.0.3440.75 (Official Build) Built on Ubuntu , running on LinuxMint 18.3 (64-bit)
MetaMask 4.9.2
https://faucet.metamask.io/
> [request 1 Ether from Faucat]
> timeout error

![metamask ether faucet - error](https://user-images.githubusercontent.com/25609/43989984-f2d7db08-9d97-11e8-8bdb-8455f1969f5a.png)

**Comment by kumavis** [comment]
seems our faucet was temporarily overwhelmed, thanks for the report
